### ISSUE TITLE
Lead-ins: Lead-in's are overlapping on devices 

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Auservice-Global#29]
Devices: I pad mini (P) and I pad (P)

![leadins](https://cloud.githubusercontent.com/assets/13309730/9992655/1748a464-6091-11e5-8a6b-a26b977fc544.png)

**Comment by Santosh-titan** [comment]
Its Not a bug. As per the design there no space between lead-ins. Now I added margin bottom 1px.
