### ISSUE TITLE
Banner section: Next and previous buttons should not move along with banner 

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Auservice-Global#31]
![welcome to01](https://cloud.githubusercontent.com/assets/13309730/9993393/2a21b0fe-6095-11e5-8d1d-73c16716d810.png)

**Comment by Santosh-titan** [comment]
As of now I added navigation arrows with in the slider image container. because of this no need to style for each and every break point and even no use to click on navigation arrows when sliding the images. Please confirm this with Team Leader.
