### ISSUE TITLE
Looking-for-work page: 'Contact us now' button Hover effect sweep to right is not working on IE9.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Auservice-Global#45]
1. Applicable for 'Read-more' and 'Submit' buttons also.

![btn-style01](https://cloud.githubusercontent.com/assets/13309730/10186623/26bd0c38-6770-11e5-92ed-019ec821f4f9.png)

**Comment by Santosh-titan** [comment]
Animation Property won't work for IE9 browser.
