### ISSUE TITLE
Home page: Intermittently, Read Less button where displayed instead of read more on devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Auservice-Global#49]
Devices: I pod, Samsung E7, I pad mini and I pad.

![samsung-e7](https://cloud.githubusercontent.com/assets/13309730/10219782/85a69d96-685f-11e5-9e00-8a4df0ccdc89.png)

**Comment by Santosh-titan** [comment]
This issue is coming from jquery.read.slide.more.js file on line no 94 
Need to update following code:
$( window ).on('resize', function() {
    height = get_new_height();
    elemrm.css('height', height+'px');
});

But we don't have permission to edit core titan file. This is common issues for all sites, need to inform this to Jolene
