### ISSUE TITLE
Header Section - IE: There are instances that the Contact Us main menu nav goes to the next line

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Auservice-Global#59]
![image](https://cloud.githubusercontent.com/assets/13363508/10358996/ada26304-6dc6-11e5-86ff-86c249d4888b.png)

**Comment by Santosh-titan** [comment]
Its working fine in my system

**Comment by maehtitan** [comment]
IE9: Try clearing your cache and observe the main menu nav after the first load, the contact us really goes to the next line or it is dropped, but it will be working fine If I load the page the 2nd time.

![image](https://cloud.githubusercontent.com/assets/13363508/10626888/1e86406c-77e6-11e5-834a-03656b913457.png)
