### ISSUE TITLE
Sidebar - Section: Sidebar is not sticky anymore when you are scrolling down the footer

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Auservice-Global#64]
![image](https://cloud.githubusercontent.com/assets/13363508/10359625/e05cf15a-6dcc-11e5-93ac-5e78ad55e15c.png)

**Comment by Santosh-titan** [comment]
Its working fine on my side in all browsers. see the screenshot

![sidebar](https://cloud.githubusercontent.com/assets/13828562/10571134/96a55c88-7659-11e5-8ffb-4f2df1e3d6aa.png)
