### ISSUE TITLE
Header - Section: I wanted to clarify if it is included in the sweep to right hover effect coz it doesn't mentioned where to apply it including the submenu hover effects

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Auservice-Global#66]
![image](https://cloud.githubusercontent.com/assets/13363508/10360009/04c338a8-6dd0-11e5-8a8f-e1644a556e13.png)

**Comment by Santosh-titan** [comment]
sweep to right hover effect has been added for top navigation
