### ISSUE TITLE
General: Icons are not using font awesome, most of it using images, was it implemented by the way?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Auservice-Global#70]
![image](https://cloud.githubusercontent.com/assets/13363508/10360816/64df37e0-6dd6-11e5-97c1-891e3226dd0f.png)

**Comment by Santosh-titan** [comment]
We have to use font awesome icons for email and phone on top header, But font awesome don't have icons for given design.

**Comment by maehtitan** [comment]
How about the leadins icon? Is there an equivalent icon for that in font-awesome?

**Comment by Santosh-titan** [comment]
font-awesome don't have lead-in icons

**Comment by maehtitan** [comment]
Thanks
