### ISSUE TITLE
Looking for work and Looking for Employees: There should be a default no-image since there is a contact button below by default

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Auservice-Global#73]
![image](https://cloud.githubusercontent.com/assets/13363508/10361506/232c5274-6ddb-11e5-820d-f598aff9ddc1.png)

**Comment by Santosh-titan** [comment]
As Per the KB standard we  should not display default no-image for list items
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/default-no-image

**Comment by maehtitan** [comment]
This is an exception since there is a Contact button below the image as per TL, it is seems too awkward to not put anything above. Marking this one as enhancement and bug (to caught your attention)
