### ISSUE TITLE
Why is it that the LOOKING FOR EMPLOYEES accepts featured image but the LOOKING FOR WORK doesn't accept when I noticed that the LOOKING FOR EMPLOYEES is basing from the LOOKING FOR WORK Template?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Auservice-Global#75]
![image](https://cloud.githubusercontent.com/assets/13363508/10362135/4553ee4e-6ddf-11e5-9fcc-d95a56aa83c0.png)

**Comment by Santosh-titan** [comment]
LOOKING FOR WORK page accepting featured image, I see there was no featured image. I have added featured image for this page. Please check it
