### ISSUE TITLE
Gallery page: The pagination style doesn't match the rest of the design

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Auservice-Global#8]
![gallery_pag01](https://cloud.githubusercontent.com/assets/13309730/9987964/342c7898-606a-11e5-8e9c-bc55cf75ee94.png)

**Comment by Santosh-titan** [comment]
We can't style nextgen gallery pagination.

**Comment by mahender-sowedane** [comment]
1. Pagination is missing on gallery page.


![gallery - pagination01](https://cloud.githubusercontent.com/assets/13309730/10192718/f2ee3c70-679b-11e5-90b9-85f44dffaf21.png)
